#!/usr/bin/env bash
# Copyright (c) 2020 Xvezda <xvezda@naver.com>
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.


if [ -z "$1" ]; then
    >&2 echo "usage: $0 <url>"
    exit
fi

BURL_VERSION="1.0.0"

URL="$1"

case "$URL" in
    http://*)
        URL_SCHEME="http"
        # Remove scheme
        PREV_URL="$URL"
        URL="${URL#${URL_SCHEME}://}"
        ;;
    *)
        ;;
esac

# Remove auth infos
PREV_URL="$URL"
URL="${URL#*@}"
URL_AUTH="${PREV_URL%${URL}}"
URL_AUTH="${URL_AUTH%@}"

# Remove paths
URL_HOST="${URL%%/*}"
URL_PATH="${URL#${URL_HOST}}"
PREV_URL="$URL"
URL="${URL%${URL_PATH}}"

# Remove port
URL_HOSTNAME="${URL%:[0-9]*}"

# Get port
URL_PORT="${URL#${URL_HOSTNAME}}"
URL_PORT="${URL_PORT:1}"
URL_PORT="${URL_PORT:-80}"

if [ ! -z "$DEBUG" ]; then
    echo "auth: $URL_AUTH"
    echo "host: $URL_HOST"
    echo "path: $URL_PATH"
    echo "port: $URL_PORT"
    echo "hostname: $URL_HOSTNAME"
fi

exec 5<>/dev/tcp/$URL_HOSTNAME/$URL_PORT
if [ $? -eq 1 ]; then
    >&2 echo "$0: fail to connect $URL_HOSTNAME"
    exit 1
fi

# Send HTTP request
echo -e "GET $URL_PATH HTTP/1.0" >&5
echo -e "Host: $URL_HOSTNAME" >&5
echo -e "User-Agent: burl/$BURL_VERSION" >&5
echo -e "Connection: close" >&5
echo -e "" >&5


HTTP_RESPONSE="$(cat <&5)"
RES_HEX="$(echo -n "$HTTP_RESPONSE" | xxd -p | tr -d $'\n')"
RES_HEAD="$(echo -n "${RES_HEX%%0d0a0d0a*}" | xxd -p -r)"
RES_BODY="$(echo -n "${RES_HEX#*0d0a0d0a}" | xxd -p -r)"

echo "$RES_BODY"

# Close file descriptor
exec 5<&-

