#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyright (c) 2019 Xvezda <https://xvezda.com/>
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.
# ===============================
# ✊ Fist; Fast gist creator script

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import sys
import json
import argparse


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--dry', '-d')
    args = parser.parse_args()
    content = sys.stdin.read()
    obj = {'content': content}
    print(json.dumps(obj))
    # try
    #     import asdf
    # except ImportError as err:
    #     print("boo")


main()

# vim:ft=python
