#!/usr/bin/env bash
# Copyright (c) 2020 Xvezda <xvezda@naver.com>
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.



ARGS=$*
SERVER_HOST="0.0.0.0"
SERVER_PORT=8000

function debug_print() {
    if [ ! -z "$DEBUG" ]; then
        echo "$@"
    fi
}

function usage() {
    echo "usage: $0 [-h] [-p [PORT]]"
}

while getopts p:h ARGS; do
    case $ARGS in
        p)
            SERVER_PORT=$OPTARG
            ;;
        h)
            usage
            exit 1
            ;;
        \?)
            exit 1
            ;;
    esac
done

debug_print "PORT: $SERVER_PORT"

if [ ! -z "$(type python)" ]; then
    python -m SimpleHTTPServer "$SERVER_PORT"
elif [ ! -z "$(type python3)" ]; then
    python3 -m http.server "$SERVER_PORT"
elif [ ! -z "$(type php)" ]; then
    php -S "$SERVER_HOST:$SERVER_PORT"
fi
