#!/usr/bin/env bash
# Copyright (c) 2020 Xvezda <xvezda@naver.com>
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.


SERVER_PORT=

exit

if [ ! -z "$(type python)" ]; then
    python -m SimpleHTTPServer
elif [ ! -z "$(type python3)" ]; then
    python3 -m http.server
elif [ ! -z "$(type php)" ]; then
    php -S $SERVER_PORT
fi
