#!/usr/bin/env bash
# Copyright (c) 2020 Xvezda <xvezda@naver.com>
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.

LC_ALL=C

for (( i=0; i<${#1}; i++ )); do
    : "${1:$i:1}"
    printf '\%o' "'$_"
done
echo
