#!/usr/bin/env bash
# Copyright (c) 2020 Xvezda <https://xvezda.com/>
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.

sed -E 's/\x1b\[[0-9~;]*[a-zA-Z]//g'
