#!/usr/bin/env bash
# Copyright (c) 2020 Xvezda <https://xvezda.com/>
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.


if [ ! -z "$(type $1 | grep 'shell builtin$')" ]; then
    eval "2>/dev/null $@"
else
    eval "$@ 2>/dev/null"
fi

# vim:ft=sh
